# Generated by Django 5.2.7 on 2025-10-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите заголовок поста", max_length=100, verbose_name="Заголовок"),
                ),
                ("content", models.TextField(help_text="Введите содержимое поста", verbose_name="Содержимое")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="preview/",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Введите дату создания записи",
                        null=True,
                        verbose_name="Дата создания",
                    ),
                ),
                ("publicate", models.BooleanField(default=True, verbose_name="Признак публикации")),
                ("views", models.IntegerField(verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
