# Generated by Django 5.2.7 on 2025-10-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
