# Generated by Django 5.2.7 on 2025-10-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
