# Generated by Django 5.2.7 on 2025-11-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpost_notified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(verbose_name="Содержимое"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="notified",
            field=models.BooleanField(default=False, verbose_name="Уведомление"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="preview",
            field=models.ImageField(blank=True, null=True, upload_to="preview/", verbose_name="Превью"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Заголовок"),
        ),
    ]
