# Generated by Django 5.2.7 on 2025-10-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(help_text="Введите страну", max_length=150, verbose_name="Страна")),
                ("inn", models.CharField(help_text="Введите ИНН", max_length=150, verbose_name="ИНН")),
                ("address", models.CharField(help_text="Введите адрес", max_length=150, verbose_name="Адрес")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
